// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQdhIi0wtM1DJ72hNVLL5g0QnkdQAf5hU',
    appId: '1:536472079677:web:b9031977dc1c1e82184954',
    messagingSenderId: '536472079677',
    projectId: 'proyek-ambw-kelompok-15',
    authDomain: 'proyek-ambw-kelompok-15.firebaseapp.com',
    storageBucket: 'proyek-ambw-kelompok-15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcHO71NWzo5GCWnL-_CSshMh4rW-HcxR0',
    appId: '1:536472079677:android:4613caf7ffc2c70d184954',
    messagingSenderId: '536472079677',
    projectId: 'proyek-ambw-kelompok-15',
    storageBucket: 'proyek-ambw-kelompok-15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqBvxunA2ydqOmgtsku-W7NQphOudgTNk',
    appId: '1:536472079677:ios:4be85d8b7038109d184954',
    messagingSenderId: '536472079677',
    projectId: 'proyek-ambw-kelompok-15',
    storageBucket: 'proyek-ambw-kelompok-15.appspot.com',
    iosClientId: '536472079677-sagbblcnfnm2ec72ouq9ihfmebodk5lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyekAmbwKel15',
  );
}
